author: Alexander Guz
url: https://guzalexander.com
encoding: UTF-8
markdown: kramdown
highlighter: rouge
paginate: 15
plugins: [jekyll-paginate, jekyll-feed]

defaults:
  -
    scope:
      type: "posts"
    values:
      layout: post
      is_post: true
