author: Alexander Guz
url: http://guzalexander.com
encoding: UTF-8
markdown: kramdown
highlighter: rouge
paginate: 30
gems: [jekyll-paginate]

defaults:
  -
    scope:
      type: "posts"
    values:
      comments: true
