author: Alexander Guz
url: https://guzalexander.com
encoding: UTF-8
markdown: kramdown
highlighter: rouge
paginate: 15
plugins: [jekyll-paginate, jekyll-feed]

collections:
  projects:
    output: true
    sort_by: "weight"

defaults:
  -
    scope:
      type: "posts"
    values:
      layout: post
      comments: true
      is_post: true
  -
    scope:
      type: "projects"
    values:
      layout: page
      comments: true
