author: Alexander Guz
url: https://guzalexander.com
title: Alexander Guz's blog
locale: en_US
encoding: UTF-8
markdown: kramdown
highlighter: rouge
paginate: 15
plugins:
  - jekyll-paginate
  - jekyll-feed
  - jekyll_picture_tag
  - jekyll-seo-tag

twitter:
  username: kalimatas
  card: summary_large_image

social:
  name: Alexander Guz
  links:
    - https://twitter.com/kalimatas
    - https://github.com/kalimatas
    - https://linkedin.com/in/kalimatas

defaults:
  -
    scope:
      type: "posts"
    values:
      layout: post
      is_post: true
